server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/json


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdemo
    username: root
    password: qazwsx


mybatis:
  typeAliasesPackage: org.andylabs.demo.domain
  mapperLocations: classpath*:**/mappers/*.xml